.TH TATAMI 1 tatami\-0.1

.SH NAME
tatami \- A tiling window manager

.SH SYNOPSIS
.B tatami
.RB [\fIoptions\fP]

.SH DESCRIPTION
Tatami is a tiling window manager for X11.
.P

.SH OPTIONS
.TP
.B \-h, \-\-help
prints a help text to standard output.

.TP
.B \-l, \-\-listen <path>
Path of the UNIX socket to listen on

.TP
.B \-q, \-\-quiet
Be more quiet

.TP
.B \-v, \-\-verbose
Be more verbose


.SH AUTHORS
.B Matthias Kruk
